version: '3.8'
services:
  api-gateway:
    build: .
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:      
      - ./:/usr/src/app/
    command: npm run start:dev
    networks:
      - mynetwork


networks:
  mynetwork:
    name: mynetwork